name = "litemcp-example-server"
main = "dist/index.js"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[vars]
MCP_SERVER_NAME = "LiteMCP BTC Price Server"
MCP_SERVER_VERSION = "1.0.0"

[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"